"""Add latitude and longitude

Revision ID: 266ac36ac10f
Revises: 
Create Date: 2025-08-22 01:43:11.478988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '266ac36ac10f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grievance_number', sa.String(), nullable=True),
    sa.Column('complaint_text', sa.String(), nullable=True),
    sa.Column('issue_type', sa.String(), nullable=True),
    sa.Column('urgency', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_grievance_number'), 'predictions', ['grievance_number'], unique=True)
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_grievance_number'), table_name='predictions')
    op.drop_table('predictions')
    # ### end Alembic commands ###
